let g:syntastic_enable_python_checker = 'python'
let g:syntastic_enable_c_checker = 'clang_check'
let g:syntastic_enable_javascript_checker = ['flow']
let g:syntastic_auto_jump = 3
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_close = 1
let g:syntastic_enable_signs = 1
let g:syntastic_warning_symbol  = '⚠ '
let g:syntastic_style_warning_symbol = '⚠ '
let g:syntastic_error_symbol = '✗'
let g:syntastic_style_error_symbol = '✗'
